services:
  - type: web
    name: myfolio
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node src/index.js
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
